/**
 *
 */
package de.unisb.cs.st.javaslicer.dependencyAnalysis;

public enum VisitorCapabilities {
    DATA_DEPENDENCIES_ALL,
    DATA_DEPENDENCIES_READ_AFTER_WRITE,
    DATA_DEPENDENCIES_WRITE_AFTER_READ,
    CONTROL_DEPENDENCIES,
    INSTRUCTION_EXECUTIONS,
    PENDING_CONTROL_DEPENDENCIES,
    PENDING_DATA_DEPENDENCIES_ALL,
    PENDING_DATA_DEPENDENCIES_READ_AFTER_WRITE,
    PENDING_DATA_DEPENDENCIES_WRITE_AFTER_READ,
}